btn+accordion-finished
js-tasks-ru/htmlcss-20221107_boba-bibap pull request #3
Opened 2022-11-21 03:25 UTC by ItCreatorNik

2022-11-21 21:05 UTC, GSemikozov requested changes

2022-11-21 21:05 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    font-size: 16px;
не хватает font-family

2022-11-21 21:05 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    cursor:default;
лучше pointer-events: none

2022-11-21 21:05 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    transition: opacity 200ms ease-in-out, background 200ms ease-in-out;
transition общий для всех типов кнопок, в таком случае надо задавать 1 раз на уровне .button

2022-11-21 21:05 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    margin-bottom: 8px;
марджины на уровне блока в БЭМ не задаем, и по структуре блока здесь напрашивается создание элемента .accordion__item / .accordion__section

2022-11-21 21:11 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-11-21 23:07 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-11-22 16:34 UTC, GSemikozov requested changes

2022-11-22 16:34 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +.accordion__section {
лишнее ограничение, удалим

2022-11-22 16:53 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-11-22 16:58 UTC, GSemikozov approved these changes

2022-11-22 16:59 UTC, merged