histogram-finished
js-tasks-ru/htmlcss-20221107_boba-bibap pull request #4
Opened 2022-12-03 00:26 UTC by ItCreatorNik

2022-12-03 00:27 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-12-06 07:10 UTC, GSemikozov requested changes

2022-12-06 07:10 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.container_histogram {
лишнее, удалим (у нас блок Гистограмма, а это - модификатор контейнера, причем очень специфический и нужен только на этой странице (нужен ли?))

2022-12-06 07:10 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    width: 9px;
flex-basis: 9px

2022-12-07 16:41 UTC, GSemikozov approved these changes

2022-12-07 16:42 UTC, merged